Repository corteva/geocube, pull requests merged in 2024-06, with the labels that each got.

#174 CI: Add latest dependencies test workflow
  .github/workflows/tests.yaml
Labels: cicd

#175 DEP: Pin geopandas<1 & numpy<2
  .github/workflows/tests.yaml
  pyproject.toml
Labels: dependencies

#176 DEP: Update to geopandas 1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/installation_issues.md
  .github/workflows/tests.yaml
  docs/getting_started.rst
  geocube/_show_versions.py
  geocube/geo_utils/geobox.py
  geocube/xarray_extensions/vectorxarray.py
  mypy.ini
  pyproject.toml
  test/unit/test_show_versions.py
Labels: dependencies

#83 DOC: clarify text in grid_to_vector_map.ipynb
  docs/examples/grid_to_vector_map.ipynb
Labels: documentation
